#!/bin/bash

# arguments
# $1 le nom de base
# $2 le rang de départ
# $3 $4 ... les images

# sortie
# le code XML à inclure dans l'archive
# les photos et les miniatures (dans le répertoire IMG)

GL=~/PUBLIC-WWW/GL
IMG="$GL/IMG"
OUTILS="$GL/OUTILS"
HTML="slide.xml"

BASE="$1"
N=$2
shift 2

# transforme les images
$OUTILS/mknormal $BASE $N "$*"

# crée les miniatures
$OUTILS/mkminip "$BASE??.jpg"

# crée le code HTML

for NAME in $BASE??.jpg ; do
  echo "<photo fichier=\"${NAME##*/}\" commentaire=\"\"/>" >>$HTML
done

exit 0
